/*
 * Level.h
 *
 *  Created on: 28/12/2015
 *      Author: joao-marcos
 */

#ifndef LEVEL_H_
#define LEVEL_H_
#include <GL/gl.h>
#include <GL/glut.h>
#include <stdlib.h>
#include <stdbool.h>
#include <stdio.h>
#include <time.h>
#include <string.h>
#include <math.h>

char mapPac[LIN][COL]={
		"XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX",
		"X.............................X",
		"X.XXXXXXXXXXX.XXX.XXXXXXXXXXX.X",
		"X.XXXXXXXXXXX.XXX.XXXXXXXXXXX.X",
		"X......XXX....XXX....XXX......X",
		"XXX.XX.XXX.XXXXXXXXX.XXX.XX.XXX",
		"XXX.XX.XXX.XXXXXXXXX.XXX.XX.XXX",
		"X*..XX.........C.........XX..*X",
		"X.XXXX.XXXXXX.XXX.XXXXXX.XXXX.X",
		"X.XXXX.XXXXXX.XXX.XXXXXX.XXXX.X",
		"X.............XXX.............X",
		"XXXXXX.XXX XXXXXXXXX XXX.XXXXXX",
		"XXXXXX.XXX XXXXXXXXX XXX.XXXXXX",
		"XXXXXX.XXX           XXX.XXXXXX",
		"XXXXXX.XXX XXXXXXXXX XXX.XXXXXX",
		"X......XXX X       X XXX......X",
		"X.XXXX.    X       X    .XXXX.X",
		"X......XXX X       X XXX......X",
		"XXXXXX.XXX XXXX-XXXX XXX.XXXXXX",
		"XXXXXX.XXX           XXX.XXXXXX",
		"XXXXXX.XXXXXX XXX XXXXXX.XXXXXX",
		"XXXXXX.XXXXXX XXX XXXXXX.XXXXXX",
		"X......XXX....XXX....XXX......X",
		"X.XXXX.XXX.XXXXXXXXX.XXX.XXXX.X",
		"X.XXXX.XXX.XXXXXXXXX.XXX.XXXX.X",
		"X.............................X",
		"X.XXXX.XXXXXX.XXX.XXXXXX.XXXX.X",
		"X*XXXX.XXXXXX.XXX.XXXXXX.XXXX*X",
		"X.XXXX.XXXXXX.XXX.XXXXXX.XXXX.X",
		"X.............XXX.............X",
		"XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX",
};

char mapGhost[LIN][COL]={
		"XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX",
		"X            T   T            X",
		"X XXXXXXXXXXX XXX XXXXXXXXXXX X",
		"X XXXXXXXXXXX X X XXXXXXXXXXX X",
		"X  T   X X    X X    X X   T  X",
		"XXX XX X X XXXXXXXXX X X XX XXX",
		"XXX XX XXX XXXXXXXXX XXX XX XXX",
		"X   XX    T  T   T  T    XX   X",
		"X XXXX XXXXXX XXX XXXXXX XXXX X",
		"X XXXX XXXXXX X X XXXXXX XXXX X",
		"X     T   T   X X   T   T     X",
		"XXXXXX XXX XXXXXXXXX XXX XXXXXX",
		"     X X X XXXXXXXXX X X X     ",
		"     X X X           X X X     ",
		"XXXXXX X X XXXXXXXXX X X XXXXXX",
		"X      XXX X K P I X XXX      X",
		"X XXXX     X T   T X     XXXX X",
		"X      XXX X T T T X XXX      X",
		"XXXXXX X X XXXX-XXXX X X XXXXXX",
		"     X X X   T B T   X X X     ",
		"     X X XXXX XXX XXXX X X     ",
		"XXXXXX X XXXX X X XXXX X XXXXXX",
		"X      X X    X X    X X      X",
		"X XXXX X X XXXXXXXXX X X XXXX X",
		"X XXXX XXX XXXXXXXXX XXX XXXX X",
		"X     T   T  T   T  T   T     X",
		"X XXXX XXXXXX XXX XXXXXX XXXX X",
		"X X  X X    X X X X    X X  X X",
		"X XXXX XXXXXX X X XXXXXX XXXX X",
		"X     T       X X       T     X",
		"XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX",
};

char level2[LIN][COL]={
"XXXXXXXXXXXXXXXXXXXXXXXXXXX",
"X*.......................*X",
"X.XXXX.XXXXXX.XXXXXX.XXXX.X",
"X.XXXX.XXXXXX.XXXXXX.XXXX.X",
"X.XX......................X",
"X.XX.XXX.XXXX.XXXX.XXX.XX.X",
"X.XX.....XX.....XX.....XX.X",
"X.XXXX.XXXX.XXX.XXXX.XXXX.X",
"X............S............X",
"XXXXXX.XXXXXXXXXXXXX.XXXXXX",
"XXXXXX.....XX*XX.....XXXXXX",
"XXXXXXXXXX.XX.XX.XXXXXXXXXX",
"XXXXX.................XXXXX",
"XX....X.XX.XX.XX.XX.X....XX",
"XX.XXXX.XX.XX.XX.XX.XXXX.XX",
"XX......XX.XX.XX.XX......XX",
"XX.XXXX.X         X.XXXX.XX",
"XX.XXXX.X XXXXXXX X.XXXX.XX",
"X........ XX   XX ........X",
"X.XX.XXXX XXX-XXX XXXX.XX.X",
"X.XX.XXXX         XXXX.XX.X",
"X.XX.XXXX XXXXXXX XXXX.XX.X",
"X.X..XXXX XX...XX XXXX..X.X",
"X.X.XXXXX XX.X.XX XXXXX.X.X",
"X.X..........X..........X.X",
"X.XXX.XXX.XX.X.XX.XXX.XXX.X",
"X.XXX.XXX.XX...XX.XXX.XXX.X",
"X*....XXX....X....XXX....*X",
"XXXXXXXXXXXXXXXXXXXXXXXXXXX",
};

char level3[LIN][COL]={
"XXXXXXXXXXXXXXXXXXXXXXXXXXX",
"X.........................X",
"X.XXXXXXXXXXX.XXXXXXXXXXX.X",
"X.X.....XXXX...XXXX.....X.X",
"X.*.XXX......X......XXX.*.X",
"X.X.XXX.XXXXXXXXXXX.XXX.X.X",
"X.X.....................X.X",
"X.XXXXXXXXXXX.XXXXXXXXXXX.X",
"X............S............X",
"XXXX.XXXXX.XXXXX.XXXXX.XXXX",
"XX.......................XX",
"X..XXX.XXX.XX.XX.XXX.XXX..X",
"X.XXXX.....XX.XX.....XXXX.X",
"X.XXXX.XXXXXX.XXXXXX.XXXX.X",
"X.........................X",
"X.XXXXXXXX.XXXXX.XXXXXXXX.X",
"X.......XX.XXXXX.XX.......X",
"X.XX.XX.           .XX.XX.X",
"X.XX.XX.XX XXXXX XX.XX.XX.X",
"X.XX.XX.   X   X   .XX.XX.X",
"X.......XX XX-XX XX.......X",
"X.XXXXXXXX       XXXXXXXX.X",
"X........XX XXX XX........X",
"X.XX.XXX...........XXX.XX.X",
"X..*.XXX.XXX.X.XXX.XXX.*..X",
"X.XXXXX..XXX.X.XXX..XXXXX.X",
"X.XXX...XXXX.X.XXXX...XXX.X",
"X.....X......X......X.....X",
"XXXXXXXXXXXXXXXXXXXXXXXXXXX",
};

char level4[LIN][COL]={
"XXXXXXXXXXXXXXXXXXXXXXXXXXX",
"X.........................X",
"X.XXXXXX.XXXX.XXXX.XXXXXX.X",
"X.*......XXXX.XXXX......*.X",
"X.XX.XXX...XX.XX...XXX.XX.X",
"X.XX..XXXX.......XXXX..XX.X",
"X.XXX.XXXXXXX.XXXXXXX.XXX.X",
"X.....XX...........XX.....X",
"X.XXX....XXXX.XXXX....XXX.X",
"X.XXXXXX.....S.....XXXXXX.X",
"X......XXX.XXXXX.XXX......X",
"X.XXXX...............XXXX.X",
"X.XX...XXXXXX XXXXXX...XX.X",
"X...XX.XX         XX.XX...X",
"X.XXXX.XX XXXXXXX XX.XXXX.X",
"X......   XX   XX   ......X",
"X.XXXX.XX XXX-XXX XX.XXXX.X",
"X...XX.XX         XX.XX...X",
"X.XX...XX XXX XXX XX...XX.X",
"X.XXXX...............XXXX.X",
"X......XXXX.XXX.XXXX......X",
"XXXXXX.XXXX.....XXXX.XXXXXX",
"XXXXXX.XXXX.XXX.XXXX.XXXXXX",
"X.........................X",
"X.XXX.XXX.XXX.XXX.XXX.XXX.X",
"X.X*..XX...........XX..*X.X",
"X.XXX.XX.XXXXXXXXX.XX.XXX.X",
"X.........................X",
"XXXXXXXXXXXXXXXXXXXXXXXXXXX",
};

char level5[LIN][COL]={
"XXXXXXXXXXXXXXXXXXXXXXXXXXX",
"X.........................X",
"X.XXX.XXX.XXXXXXX.XXX.XXX.X",
"X...X.XXX.XXXXXXX.XXX.X...X",
"X*X.X.................X.X*X",
"XXX.XXXXX.XXXXXXX.XXXXX.XXX",
"XXX..........S..........XXX",
"XXX.XXXXXXXX.X.XXXXXXXX.XXX",
"X............X............X",
"X.X.XXX.XXXXXXXXXXX.XXX.X.X",
"X.X.XXX.............XXX.X.X",
"X.X.XXX.XXX XXX XXX.XXX.X.X",
"X.......X         X.......X",
"X.XXX.X.X XXXXXXX X.X.XXX.X",
"X.XXX...  XX   XX  ...XXX.X",
"X.XXX.X.X XXX-XXX X.X.XXX.X",
"X.XXX.X.X         X.X.XXX.X",
"X.XXX.X.XXX XXX XXX.X.XXX.X",
"X.........................X",
"X.XXXXX.XXXXX.XXXXX.XXXXX.X",
"X...X.................X...X",
"XXX.X.XXXX.XXXXX.XXXX.X.XXX",
"XXX..........X..........XXX",
"XXX.XXXXX.XX.X.XX.XXXXX.XXX",
"X..........X.X.X..........X",
"X.XXX.XXXX.X...X.XXXX.XXX.X",
"X.XXX.XXXX.X.X.X.XXXX.XXX.X",
"X*...........X...........*X",
"XXXXXXXXXXXXXXXXXXXXXXXXXXX",
};




#endif /* LEVEL_H_ */
